title: "胡晓倩 | 学术主页"
description: "胡晓倩，首都经济贸易大学管理工程学院副教授、硕士生导师。"
lang: zh-CN
timezone: Asia/Shanghai
url: ""
baseurl: ""

author:
  name: 胡晓倩
  email: huxiaoqian@cueb.edu.cn

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
